#!/usr/bin/env python3
import sys, base64

"""
R-Law-Big
-32768/-32767 - 0
1622 intervals of +11 / -14925 - 1622
1024 intervals of +8 / -6733 - 2646
767 intervals of +6 / -2131 - 3413
516 intervals of +3 / -583 - 3929
583 intervals of +1 / -1 - 4511
0 - 4512
583 intervals of +1 / 583 - 5096
516 intervals of +3 / 2131 - 5612
767 intervals of +6 / 6733 - 6379
1024 intervals of +8 / 14925 - 7403
1622 intervals of +11 / 32767 - 9024
32767 - 9024

R-Law-Little
-512/-511 - 0
16 intervals of +16
12 intervals of +12
9 intervals of +9
5 intervals of +4
5 intervals of +2
0 - 47
5 intervals of +2
5 intervals of +4
9 intervals of +9
12 intervals of +12
16 intervals of +16
511 - 94
"""

def encode(x):
    x = max(-32767, min(32767, x))   # clamp -32768
    a = abs(x)
    if   a <= 583:   k = a
    elif a <= 2131:  k = 583  + (a - 583)  // 3
    elif a <= 6733:  k = 1099 + (a - 2131) // 6
    elif a <= 14925: k = 1866 + (a - 6733) // 8
    else:            k = 2890 + (a - 14925) // 11
    m = 4512 + (k if x >= 0 else -k)
    return encbyte(m)

def sencode(x):
    x = max(-511, min(511, x))        # clamp -512
    a = abs(x)
    if   a <= 10:  k = a // 2
    elif a <= 30:  k = 5  + (a - 10)  // 4
    elif a <= 111: k = 10 + (a - 30)  // 9
    elif a <= 255: k = 19 + (a - 111) // 12
    else:          k = 31 + (a - 255) // 16
    return chr(47 + (k if x >= 0 else -k) + 32)

def encbyte(n: int):
    i0 = n%95
    i1 = n//95
    return chr(i1+32)+chr(i0+32)

def main():
    print(f"Aperture Audio Format Encoder v0.8.4 (c) 1996")
    if len(sys.argv) < 3:
        print("""Usage: aafenc <input_file [sint16le PCM/WAV]> <output file [AAF]> --hz=<freq (Hz) [default: 24000]> --mode=<s,d [default: s]> --channels=<int [default: 1]> --desc=<string>""")
        sys.exit()
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    args = sys.argv[3:]
    freq = 24000
    mode = "s"
    channels = 1
    desc = ""
    for arg in args:
        if arg.startswith("--mode="):
            mode = arg.replace("--mode=", "")
        if arg.startswith("--desc="):
            desc = ","+arg.replace("--desc=", "")
        if arg.startswith("--hz="):
            freq = int(arg.replace("--hz=", ""))
        if arg.startswith("--channels="):
            channels = int(arg.replace("--channels=", ""))

    aud = open(input_path, "rb")
    binary = aud.read()
    blob = ","
    if binary[0:4] == b"RIFF" and binary[8:12] == b"WAVE":
        assert (int.from_bytes(binary[20:22], "little") == 1), "Unsupported Audio Format (PCM expected)"
        assert (int.from_bytes(binary[34:36], "little") == 16), "Unsupported PCM Format (sint16le expected)"
        freq = int.from_bytes(binary[24:28], "little")
        channels = int.from_bytes(binary[22:24], "little")

        seek = 36
        while seek < len(binary):
            chunk_id = bytes([binary[seek], binary[seek+1], binary[seek+2], binary[seek+3]])
            chunk_len = int.from_bytes(bytes([binary[seek+4], binary[seek+5], binary[seek+6], binary[seek+7]]), "little")
            seek += 8
            if chunk_id == b"data":
                binary = binary[seek:seek+chunk_len]
            else:
                print("Encoding chunk to XML-like comment:", chunk_id.decode("ascii"), chunk_len)
                bdata = binary[seek:seek+chunk_len]
                blob+=f"<chunk type=\"{chunk_id.decode("ascii")}\" length={chunk_len} encoding=\"base64\">{base64.b64encode(bdata).decode("ascii")}</chunk>"
            seek += chunk_len

    if not desc and not blob == ",":
        desc = blob # keep misc riff chunks
    if desc == ",":
        desc = ""

    dat = ["APERTURE AUDIO FORMAT (c) 1986\n"]
    dat.append(f"{freq},{channels},{mode}{desc}\n")
    b = bytearray()
    if mode == "d":
        for byte in binary:
            if not b:
                b.append(byte)
            else:
                b.append(byte)
                value = int.from_bytes(b, "little", signed=True)
                b.clear()
                dat.append(encode(value))
    else:
        for byte in binary:
            if not b:
                b.append(byte)
            else:
                b.append(byte)
                value = int.from_bytes(b, "little", signed=True)
                b.clear()
                dat.append(sencode(value//64))

    open(output_path, "w").write("".join(dat))

    print(f"AAF Encoded! \"{input_path}\" -> \"{output_path}\"\nAAF Mode: {mode}, Frequency: {freq}, Channels: {channels}")
if __name__ == "__main__":
    main()